name: Deploy to Amazon ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login --username AWS --password-stdin 625693792692.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build
        run: docker build -t my-app .

      - name: Tag
        run: docker tag my-app:latest 625693792692.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest

      - name: Push
        run: docker push 625693792692.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster my-cluster1 \
            --service my-service \
            --force-new-deployment \
            --region eu-north-1
