name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login --username AWS --password-stdin 625693792692.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build image
        run: docker build -t my-app .

      - name: Tag image
        run: docker tag my-app:latest 625693792692.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest

      - name: Push image
        run: docker push 625693792692.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest
